CREATE USER C##COMPANY_DB IDENTIFIED BY company;

GRANT CONNECT, RESOURCE, DBA TO C##COMPANY_DB;

ALTER USER C##COMPANY_DB DEFAULT TABLESPACE USERS;

ALTER USER C##COMPANY_DB QUOTA UNLIMITED ON USERS;

