DROP TABLE C##COMPANY_DB.order_items;  
DROP TABLE C##COMPANY_DB.orders;
DROP TABLE C##COMPANY_DB.inventories;
DROP TABLE C##COMPANY_DB.products;
DROP TABLE C##COMPANY_DB.product_categories;
DROP TABLE C##COMPANY_DB.warehouses;
DROP TABLE C##COMPANY_DB.employees;
DROP TABLE C##COMPANY_DB.contacts;
DROP TABLE C##COMPANY_DB.customers;
DROP TABLE C##COMPANY_DB.locations;
DROP TABLE C##COMPANY_DB.countries;
DROP TABLE C##COMPANY_DB.regions;


